CREATE TABLE IF NOT EXISTS `notifications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `actor_id` INT UNSIGNED NULL,
  `type` VARCHAR(64) NOT NULL,
  `entity_type` VARCHAR(64) NOT NULL,
  `entity_id` INT UNSIGNED NULL,
  `related_type` VARCHAR(64) NULL,
  `related_id` INT UNSIGNED NULL,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NULL,
  `url` VARCHAR(500) NULL,
  `payload_json` TEXT NULL,
  `dedupe_key` VARCHAR(191) NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `read_at` DATETIME NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `user_read_created` (`user_id`, `is_read`, `created_at`),
  KEY `user_created` (`user_id`, `created_at`),
  KEY `type_entity` (`type`, `entity_type`, `entity_id`),
  KEY `user_dedupe` (`user_id`, `dedupe_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
